// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: chat.proto

package chatpb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type C2SLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username []byte `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password []byte `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *C2SLogin) Reset() {
	*x = C2SLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SLogin) ProtoMessage() {}

func (x *C2SLogin) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SLogin.ProtoReflect.Descriptor instead.
func (*C2SLogin) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0}
}

func (x *C2SLogin) GetUsername() []byte {
	if x != nil {
		return x.Username
	}
	return nil
}

func (x *C2SLogin) GetPassword() []byte {
	if x != nil {
		return x.Password
	}
	return nil
}

type S2CLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret      RetType     `protobuf:"varint,1,opt,name=ret,proto3,enum=RetType" json:"ret,omitempty"`
	Info     *StructUser `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Lastchat []*S2CChat  `protobuf:"bytes,3,rep,name=lastchat,proto3" json:"lastchat,omitempty"`
}

func (x *S2CLogin) Reset() {
	*x = S2CLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CLogin) ProtoMessage() {}

func (x *S2CLogin) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CLogin.ProtoReflect.Descriptor instead.
func (*S2CLogin) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{1}
}

func (x *S2CLogin) GetRet() RetType {
	if x != nil {
		return x.Ret
	}
	return RetType_Success
}

func (x *S2CLogin) GetInfo() *StructUser {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *S2CLogin) GetLastchat() []*S2CChat {
	if x != nil {
		return x.Lastchat
	}
	return nil
}

type C2SRegister struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username []byte `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password []byte `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *C2SRegister) Reset() {
	*x = C2SRegister{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SRegister) ProtoMessage() {}

func (x *C2SRegister) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SRegister.ProtoReflect.Descriptor instead.
func (*C2SRegister) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{2}
}

func (x *C2SRegister) GetUsername() []byte {
	if x != nil {
		return x.Username
	}
	return nil
}

func (x *C2SRegister) GetPassword() []byte {
	if x != nil {
		return x.Password
	}
	return nil
}

type S2CRegister struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret RetType `protobuf:"varint,1,opt,name=ret,proto3,enum=RetType" json:"ret,omitempty"`
}

func (x *S2CRegister) Reset() {
	*x = S2CRegister{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CRegister) ProtoMessage() {}

func (x *S2CRegister) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CRegister.ProtoReflect.Descriptor instead.
func (*S2CRegister) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{3}
}

func (x *S2CRegister) GetRet() RetType {
	if x != nil {
		return x.Ret
	}
	return RetType_Success
}

type C2SOnlineUsers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2SOnlineUsers) Reset() {
	*x = C2SOnlineUsers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SOnlineUsers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SOnlineUsers) ProtoMessage() {}

func (x *C2SOnlineUsers) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SOnlineUsers.ProtoReflect.Descriptor instead.
func (*C2SOnlineUsers) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{4}
}

type S2COnlineUsers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret   RetType       `protobuf:"varint,1,opt,name=ret,proto3,enum=RetType" json:"ret,omitempty"`
	Users []*StructUser `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *S2COnlineUsers) Reset() {
	*x = S2COnlineUsers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2COnlineUsers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2COnlineUsers) ProtoMessage() {}

func (x *S2COnlineUsers) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2COnlineUsers.ProtoReflect.Descriptor instead.
func (*S2COnlineUsers) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{5}
}

func (x *S2COnlineUsers) GetRet() RetType {
	if x != nil {
		return x.Ret
	}
	return RetType_Success
}

func (x *S2COnlineUsers) GetUsers() []*StructUser {
	if x != nil {
		return x.Users
	}
	return nil
}

type C2SChat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgType MsgType `protobuf:"varint,1,opt,name=msgType,proto3,enum=MsgType" json:"msgType,omitempty"`
	ToUid   uint32  `protobuf:"varint,2,opt,name=toUid,proto3" json:"toUid,omitempty"`
	ToNick  []byte  `protobuf:"bytes,3,opt,name=toNick,proto3" json:"toNick,omitempty"`
	Msg     []byte  `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *C2SChat) Reset() {
	*x = C2SChat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SChat) ProtoMessage() {}

func (x *C2SChat) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SChat.ProtoReflect.Descriptor instead.
func (*C2SChat) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{6}
}

func (x *C2SChat) GetMsgType() MsgType {
	if x != nil {
		return x.MsgType
	}
	return MsgType_eMsg_All
}

func (x *C2SChat) GetToUid() uint32 {
	if x != nil {
		return x.ToUid
	}
	return 0
}

func (x *C2SChat) GetToNick() []byte {
	if x != nil {
		return x.ToNick
	}
	return nil
}

func (x *C2SChat) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

type S2CChat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret      RetType `protobuf:"varint,1,opt,name=ret,proto3,enum=RetType" json:"ret,omitempty"`
	MsgType  MsgType `protobuf:"varint,2,opt,name=msgType,proto3,enum=MsgType" json:"msgType,omitempty"`
	FromUid  uint32  `protobuf:"varint,3,opt,name=fromUid,proto3" json:"fromUid,omitempty"`
	ToUid    uint32  `protobuf:"varint,4,opt,name=toUid,proto3" json:"toUid,omitempty"`
	FromNick []byte  `protobuf:"bytes,5,opt,name=fromNick,proto3" json:"fromNick,omitempty"`
	ToNick   []byte  `protobuf:"bytes,6,opt,name=toNick,proto3" json:"toNick,omitempty"`
	Msg      []byte  `protobuf:"bytes,7,opt,name=msg,proto3" json:"msg,omitempty"`
	SendTime uint64  `protobuf:"varint,8,opt,name=sendTime,proto3" json:"sendTime,omitempty"`
}

func (x *S2CChat) Reset() {
	*x = S2CChat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CChat) ProtoMessage() {}

func (x *S2CChat) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CChat.ProtoReflect.Descriptor instead.
func (*S2CChat) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{7}
}

func (x *S2CChat) GetRet() RetType {
	if x != nil {
		return x.Ret
	}
	return RetType_Success
}

func (x *S2CChat) GetMsgType() MsgType {
	if x != nil {
		return x.MsgType
	}
	return MsgType_eMsg_All
}

func (x *S2CChat) GetFromUid() uint32 {
	if x != nil {
		return x.FromUid
	}
	return 0
}

func (x *S2CChat) GetToUid() uint32 {
	if x != nil {
		return x.ToUid
	}
	return 0
}

func (x *S2CChat) GetFromNick() []byte {
	if x != nil {
		return x.FromNick
	}
	return nil
}

func (x *S2CChat) GetToNick() []byte {
	if x != nil {
		return x.ToNick
	}
	return nil
}

func (x *S2CChat) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *S2CChat) GetSendTime() uint64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

type C2SChatCntTopUsers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start uint32 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	Cnt   uint32 `protobuf:"varint,2,opt,name=cnt,proto3" json:"cnt,omitempty"`
}

func (x *C2SChatCntTopUsers) Reset() {
	*x = C2SChatCntTopUsers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SChatCntTopUsers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SChatCntTopUsers) ProtoMessage() {}

func (x *C2SChatCntTopUsers) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SChatCntTopUsers.ProtoReflect.Descriptor instead.
func (*C2SChatCntTopUsers) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{8}
}

func (x *C2SChatCntTopUsers) GetStart() uint32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *C2SChatCntTopUsers) GetCnt() uint32 {
	if x != nil {
		return x.Cnt
	}
	return 0
}

type S2CChatCntTopUsers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret   RetType       `protobuf:"varint,1,opt,name=ret,proto3,enum=RetType" json:"ret,omitempty"`
	Users []*StructUser `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *S2CChatCntTopUsers) Reset() {
	*x = S2CChatCntTopUsers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CChatCntTopUsers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CChatCntTopUsers) ProtoMessage() {}

func (x *S2CChatCntTopUsers) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CChatCntTopUsers.ProtoReflect.Descriptor instead.
func (*S2CChatCntTopUsers) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{9}
}

func (x *S2CChatCntTopUsers) GetRet() RetType {
	if x != nil {
		return x.Ret
	}
	return RetType_Success
}

func (x *S2CChatCntTopUsers) GetUsers() []*StructUser {
	if x != nil {
		return x.Users
	}
	return nil
}

type C2SHeartBeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2SHeartBeat) Reset() {
	*x = C2SHeartBeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SHeartBeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SHeartBeat) ProtoMessage() {}

func (x *C2SHeartBeat) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SHeartBeat.ProtoReflect.Descriptor instead.
func (*C2SHeartBeat) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{10}
}

type S2CStatusChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret    RetType     `protobuf:"varint,1,opt,name=ret,proto3,enum=RetType" json:"ret,omitempty"`
	User   *StructUser `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Status UserStatus  `protobuf:"varint,3,opt,name=status,proto3,enum=UserStatus" json:"status,omitempty"`
}

func (x *S2CStatusChange) Reset() {
	*x = S2CStatusChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CStatusChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CStatusChange) ProtoMessage() {}

func (x *S2CStatusChange) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CStatusChange.ProtoReflect.Descriptor instead.
func (*S2CStatusChange) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{11}
}

func (x *S2CStatusChange) GetRet() RetType {
	if x != nil {
		return x.Ret
	}
	return RetType_Success
}

func (x *S2CStatusChange) GetUser() *StructUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *S2CStatusChange) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_eStatus_Online
}

type C2SChatCnt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nick []byte `protobuf:"bytes,1,opt,name=nick,proto3" json:"nick,omitempty"`
}

func (x *C2SChatCnt) Reset() {
	*x = C2SChatCnt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SChatCnt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SChatCnt) ProtoMessage() {}

func (x *C2SChatCnt) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SChatCnt.ProtoReflect.Descriptor instead.
func (*C2SChatCnt) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{12}
}

func (x *C2SChatCnt) GetNick() []byte {
	if x != nil {
		return x.Nick
	}
	return nil
}

type S2CChatCnt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret     RetType `protobuf:"varint,1,opt,name=ret,proto3,enum=RetType" json:"ret,omitempty"`
	Nick    []byte  `protobuf:"bytes,2,opt,name=nick,proto3" json:"nick,omitempty"`
	Chatcnt uint32  `protobuf:"varint,3,opt,name=chatcnt,proto3" json:"chatcnt,omitempty"`
}

func (x *S2CChatCnt) Reset() {
	*x = S2CChatCnt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CChatCnt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CChatCnt) ProtoMessage() {}

func (x *S2CChatCnt) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CChatCnt.ProtoReflect.Descriptor instead.
func (*S2CChatCnt) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{13}
}

func (x *S2CChatCnt) GetRet() RetType {
	if x != nil {
		return x.Ret
	}
	return RetType_Success
}

func (x *S2CChatCnt) GetNick() []byte {
	if x != nil {
		return x.Nick
	}
	return nil
}

func (x *S2CChatCnt) GetChatcnt() uint32 {
	if x != nil {
		return x.Chatcnt
	}
	return 0
}

var File_chat_proto protoreflect.FileDescriptor

var file_chat_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x42, 0x0a, 0x08, 0x43, 0x32,
	0x53, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x6d,
	0x0a, 0x08, 0x53, 0x32, 0x43, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x03, 0x72, 0x65,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x08, 0x2e, 0x52, 0x65, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x1f, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x24, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x63,
	0x68, 0x61, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x53, 0x32, 0x43, 0x43,
	0x68, 0x61, 0x74, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x63, 0x68, 0x61, 0x74, 0x22, 0x45, 0x0a,
	0x0b, 0x43, 0x32, 0x53, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x22, 0x29, 0x0a, 0x0b, 0x53, 0x32, 0x43, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x08, 0x2e, 0x52, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x03, 0x72, 0x65, 0x74, 0x22,
	0x10, 0x0a, 0x0e, 0x43, 0x32, 0x53, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x73, 0x22, 0x4f, 0x0a, 0x0e, 0x53, 0x32, 0x43, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x73, 0x12, 0x1a, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x08, 0x2e, 0x52, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12,
	0x21, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x75, 0x73, 0x65,
	0x72, 0x73, 0x22, 0x6d, 0x0a, 0x07, 0x43, 0x32, 0x53, 0x43, 0x68, 0x61, 0x74, 0x12, 0x22, 0x0a,
	0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x08,
	0x2e, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x55, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x74, 0x6f, 0x55, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x4e, 0x69, 0x63,
	0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x74, 0x6f, 0x4e, 0x69, 0x63, 0x6b, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x22, 0xdb, 0x01, 0x0a, 0x07, 0x53, 0x32, 0x43, 0x43, 0x68, 0x61, 0x74, 0x12, 0x1a, 0x0a,
	0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x08, 0x2e, 0x52, 0x65, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x22, 0x0a, 0x07, 0x6d, 0x73, 0x67,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x08, 0x2e, 0x4d, 0x73, 0x67,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x66, 0x72, 0x6f, 0x6d, 0x55, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x55, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x6f, 0x55, 0x69, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x66, 0x72, 0x6f, 0x6d, 0x4e, 0x69, 0x63, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x08, 0x66, 0x72, 0x6f, 0x6d, 0x4e, 0x69, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x4e,
	0x69, 0x63, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x74, 0x6f, 0x4e, 0x69, 0x63,
	0x6b, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22,
	0x3c, 0x0a, 0x12, 0x43, 0x32, 0x53, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6e, 0x74, 0x54, 0x6f, 0x70,
	0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x63,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x63, 0x6e, 0x74, 0x22, 0x53, 0x0a,
	0x12, 0x53, 0x32, 0x43, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6e, 0x74, 0x54, 0x6f, 0x70, 0x55, 0x73,
	0x65, 0x72, 0x73, 0x12, 0x1a, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x08, 0x2e, 0x52, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12,
	0x21, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x75, 0x73, 0x65,
	0x72, 0x73, 0x22, 0x0e, 0x0a, 0x0c, 0x43, 0x32, 0x53, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65,
	0x61, 0x74, 0x22, 0x73, 0x0a, 0x0f, 0x53, 0x32, 0x43, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x08, 0x2e, 0x52, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x03, 0x72, 0x65,
	0x74, 0x12, 0x1f, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x12, 0x23, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x20, 0x0a, 0x0a, 0x43, 0x32, 0x53, 0x43, 0x68,
	0x61, 0x74, 0x43, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x69, 0x63, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x6e, 0x69, 0x63, 0x6b, 0x22, 0x56, 0x0a, 0x0a, 0x53, 0x32, 0x43,
	0x43, 0x68, 0x61, 0x74, 0x43, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x08, 0x2e, 0x52, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x03,
	0x72, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x69, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x6e, 0x69, 0x63, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x74, 0x63,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x68, 0x61, 0x74, 0x63, 0x6e,
	0x74, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x3b, 0x63, 0x68, 0x61, 0x74, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chat_proto_rawDescOnce sync.Once
	file_chat_proto_rawDescData = file_chat_proto_rawDesc
)

func file_chat_proto_rawDescGZIP() []byte {
	file_chat_proto_rawDescOnce.Do(func() {
		file_chat_proto_rawDescData = protoimpl.X.CompressGZIP(file_chat_proto_rawDescData)
	})
	return file_chat_proto_rawDescData
}

var file_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_chat_proto_goTypes = []interface{}{
	(*C2SLogin)(nil),           // 0: C2SLogin
	(*S2CLogin)(nil),           // 1: S2CLogin
	(*C2SRegister)(nil),        // 2: C2SRegister
	(*S2CRegister)(nil),        // 3: S2CRegister
	(*C2SOnlineUsers)(nil),     // 4: C2SOnlineUsers
	(*S2COnlineUsers)(nil),     // 5: S2COnlineUsers
	(*C2SChat)(nil),            // 6: C2SChat
	(*S2CChat)(nil),            // 7: S2CChat
	(*C2SChatCntTopUsers)(nil), // 8: C2SChatCntTopUsers
	(*S2CChatCntTopUsers)(nil), // 9: S2CChatCntTopUsers
	(*C2SHeartBeat)(nil),       // 10: C2SHeartBeat
	(*S2CStatusChange)(nil),    // 11: S2CStatusChange
	(*C2SChatCnt)(nil),         // 12: C2SChatCnt
	(*S2CChatCnt)(nil),         // 13: S2CChatCnt
	(RetType)(0),               // 14: RetType
	(*StructUser)(nil),         // 15: StructUser
	(MsgType)(0),               // 16: MsgType
	(UserStatus)(0),            // 17: UserStatus
}
var file_chat_proto_depIdxs = []int32{
	14, // 0: S2CLogin.ret:type_name -> RetType
	15, // 1: S2CLogin.info:type_name -> StructUser
	7,  // 2: S2CLogin.lastchat:type_name -> S2CChat
	14, // 3: S2CRegister.ret:type_name -> RetType
	14, // 4: S2COnlineUsers.ret:type_name -> RetType
	15, // 5: S2COnlineUsers.users:type_name -> StructUser
	16, // 6: C2SChat.msgType:type_name -> MsgType
	14, // 7: S2CChat.ret:type_name -> RetType
	16, // 8: S2CChat.msgType:type_name -> MsgType
	14, // 9: S2CChatCntTopUsers.ret:type_name -> RetType
	15, // 10: S2CChatCntTopUsers.users:type_name -> StructUser
	14, // 11: S2CStatusChange.ret:type_name -> RetType
	15, // 12: S2CStatusChange.user:type_name -> StructUser
	17, // 13: S2CStatusChange.status:type_name -> UserStatus
	14, // 14: S2CChatCnt.ret:type_name -> RetType
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_chat_proto_init() }
func file_chat_proto_init() {
	if File_chat_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_chat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SRegister); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CRegister); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SOnlineUsers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2COnlineUsers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SChat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CChat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SChatCntTopUsers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CChatCntTopUsers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SHeartBeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CStatusChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SChatCnt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CChatCnt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chat_proto_goTypes,
		DependencyIndexes: file_chat_proto_depIdxs,
		MessageInfos:      file_chat_proto_msgTypes,
	}.Build()
	File_chat_proto = out.File
	file_chat_proto_rawDesc = nil
	file_chat_proto_goTypes = nil
	file_chat_proto_depIdxs = nil
}
