// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: common.proto

package chatpb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RetType int32

const (
	RetType_Success            RetType = 0   //成功
	RetType_NormalErrpr        RetType = 1   //一般错误
	RetType_RedisError         RetType = 2   //redis执行失败
	RetType_SQLError           RetType = 3   //mysql执行失败
	RetType_PassError          RetType = 100 //密码错误
	RetType_AccountError       RetType = 101 //账号错误
	RetType_AccountExistError  RetType = 102 //账号已存在
	RetType_AccountNotStandard RetType = 103 //账号不标准
	RetType_PassNotStandard    RetType = 104 //密码不标准
	RetType_UserOffline        RetType = 105 //账号不标准
	RetType_UserOnline         RetType = 106 //账号不标准
)

// Enum value maps for RetType.
var (
	RetType_name = map[int32]string{
		0:   "Success",
		1:   "NormalErrpr",
		2:   "RedisError",
		3:   "SQLError",
		100: "PassError",
		101: "AccountError",
		102: "AccountExistError",
		103: "AccountNotStandard",
		104: "PassNotStandard",
		105: "UserOffline",
		106: "UserOnline",
	}
	RetType_value = map[string]int32{
		"Success":            0,
		"NormalErrpr":        1,
		"RedisError":         2,
		"SQLError":           3,
		"PassError":          100,
		"AccountError":       101,
		"AccountExistError":  102,
		"AccountNotStandard": 103,
		"PassNotStandard":    104,
		"UserOffline":        105,
		"UserOnline":         106,
	}
)

func (x RetType) Enum() *RetType {
	p := new(RetType)
	*p = x
	return p
}

func (x RetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RetType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (RetType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x RetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RetType.Descriptor instead.
func (RetType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type MsgType int32

const (
	MsgType_eMsg_All MsgType = 0 //通知所有
	MsgType_eMsg_One MsgType = 1 //通知一个
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "eMsg_All",
		1: "eMsg_One",
	}
	MsgType_value = map[string]int32{
		"eMsg_All": 0,
		"eMsg_One": 1,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

type UserStatus int32

const (
	UserStatus_eStatus_Online  UserStatus = 0
	UserStatus_eStatus_Offline UserStatus = 1
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "eStatus_Online",
		1: "eStatus_Offline",
	}
	UserStatus_value = map[string]int32{
		"eStatus_Online":  0,
		"eStatus_Offline": 1,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[2].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[2]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

type StructUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username      []byte `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Uid           uint32 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Regtime       uint64 `protobuf:"varint,3,opt,name=regtime,proto3" json:"regtime,omitempty"`
	Lastlogintime uint64 `protobuf:"varint,4,opt,name=lastlogintime,proto3" json:"lastlogintime,omitempty"`
	Chatcnt       uint32 `protobuf:"varint,5,opt,name=chatcnt,proto3" json:"chatcnt,omitempty"`
	Lastleavetime uint64 `protobuf:"varint,6,opt,name=lastleavetime,proto3" json:"lastleavetime,omitempty"`
}

func (x *StructUser) Reset() {
	*x = StructUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StructUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructUser) ProtoMessage() {}

func (x *StructUser) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructUser.ProtoReflect.Descriptor instead.
func (*StructUser) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *StructUser) GetUsername() []byte {
	if x != nil {
		return x.Username
	}
	return nil
}

func (x *StructUser) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *StructUser) GetRegtime() uint64 {
	if x != nil {
		return x.Regtime
	}
	return 0
}

func (x *StructUser) GetLastlogintime() uint64 {
	if x != nil {
		return x.Lastlogintime
	}
	return 0
}

func (x *StructUser) GetChatcnt() uint32 {
	if x != nil {
		return x.Chatcnt
	}
	return 0
}

func (x *StructUser) GetLastleavetime() uint64 {
	if x != nil {
		return x.Lastleavetime
	}
	return 0
}

var File_common_proto protoreflect.FileDescriptor

var file_common_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xba,
	0x01, 0x0a, 0x0a, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x72,
	0x65, 0x67, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x72, 0x65,
	0x67, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x6c, 0x61,
	0x73, 0x74, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x68, 0x61, 0x74, 0x63, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x68,
	0x61, 0x74, 0x63, 0x6e, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x6c, 0x65, 0x61,
	0x76, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x6c, 0x61,
	0x73, 0x74, 0x6c, 0x65, 0x61, 0x76, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x2a, 0xcb, 0x01, 0x0a, 0x07,
	0x52, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x45, 0x72,
	0x72, 0x70, 0x72, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x65, 0x64, 0x69, 0x73, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x51, 0x4c, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x61, 0x73, 0x73, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x10, 0x64, 0x12, 0x10, 0x0a, 0x0c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x10, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x45,
	0x78, 0x69, 0x73, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x66, 0x12, 0x16, 0x0a, 0x12, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4e, 0x6f, 0x74, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72,
	0x64, 0x10, 0x67, 0x12, 0x13, 0x0a, 0x0f, 0x50, 0x61, 0x73, 0x73, 0x4e, 0x6f, 0x74, 0x53, 0x74,
	0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x10, 0x68, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72,
	0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x10, 0x69, 0x12, 0x0e, 0x0a, 0x0a, 0x55, 0x73, 0x65,
	0x72, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x10, 0x6a, 0x2a, 0x25, 0x0a, 0x07, 0x4d, 0x73, 0x67,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x65, 0x4d, 0x73, 0x67, 0x5f, 0x41, 0x6c, 0x6c,
	0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x65, 0x4d, 0x73, 0x67, 0x5f, 0x4f, 0x6e, 0x65, 0x10, 0x01,
	0x2a, 0x35, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12,
	0x0a, 0x0e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65,
	0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x4f, 0x66,
	0x66, 0x6c, 0x69, 0x6e, 0x65, 0x10, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x3b, 0x63, 0x68, 0x61,
	0x74, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData = file_common_proto_rawDesc
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_proto_rawDescData)
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_proto_goTypes = []interface{}{
	(RetType)(0),       // 0: RetType
	(MsgType)(0),       // 1: MsgType
	(UserStatus)(0),    // 2: UserStatus
	(*StructUser)(nil), // 3: StructUser
}
var file_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StructUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_rawDesc = nil
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
